<a href="https://colab.research.google.com/github/Pushpalatha-H/ML/blob/main/13_KFold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KFold Cross Validation
**Split availabel data into 5 folds ex, then take average of individual score and average of it.**

In [21]:
import pandas as pd
import numpy as np

In [22]:
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [23]:
from sklearn import datasets
from sklearn.datasets import load_digits

In [24]:
digits = datasets.load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target)

**LogisticRegression**

In [26]:
lr =LogisticRegression()
lr.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [27]:
lr.score(x_test,y_test)

0.9644444444444444

**svm**

In [28]:
svm = svm.SVC()
svm.fit(x_train, y_train)

SVC()

In [29]:
svm.score(x_test, y_test)

0.9888888888888889

**RandomForestClassifier**

In [30]:
rf = RandomForestClassifier(n_estimators = 30)
rf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=30)

In [31]:
rf.score(x_test, y_test)

0.9711111111111111

#KFold cross validation
Using KFold for basic example

In [32]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [33]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8,9]):
  print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**Using KFold Cross Validation for digits data**

In [34]:
def get_score(model, x_train, x_test, y_train, y_test):
  model.fit(x_train, y_train)
  return model.score(x_test, y_test)

In [35]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
scores_L = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
  x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
                                     digits.target[train_index], digits.target[test_index]

  scores_L.append(get_score(LogisticRegression(solver='liblinear', multi_class='auto'), x_train, x_test, y_train, y_test))
  scores_svm.append(get_score(SVC(gamma='auto'),x_train, x_test, y_train, y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

In [36]:
scores_L

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [37]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [38]:
scores_rf

[0.9248747913188647, 0.9532554257095158, 0.9315525876460768]

#Cross Validation Score
**Cross_val_score using LogisticRegression**

In [39]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

**Cross_val_score using SVM**

In [40]:
cross_val_score(svm.SVC(gamma='auto'), digits.data, digits.target)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

**Cross_val_score using RandomForestClassifier**

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.93823038, 0.93989983, 0.91819699])

#Parameter tunning using k fold cross validation

In [45]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target, cv=10)
np.average(scores1)

0.9137368094351335

In [49]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)
np.average(scores2)

0.9376722532588456

In [52]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=10)
np.average(scores3)

0.9387740533829918

In [55]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
np.average(scores4)

0.9415704531346988

We used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.