<a href="https://colab.research.google.com/github/Pushpalatha-H/ML/blob/main/15_Naive_Bayes_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Naive Bayes

Gaussian Naive Bayesis used is a classification technique used in ML based on probablistic approach and Gaussian Distribution

P(A/B) = P(B/A) * P(A)/ P(B)

Predict Titanic survival using naive Bayes

In [20]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [22]:
df =df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis='columns')
df.head(3)

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1

In [23]:
# check if it has n.a
df.isna().sum()

Pclass        0
Sex           0
Age         177
Fare          0
Survived      0
dtype: int64

In [24]:
median = df['Age'].median()

In [25]:
#  fill n.a. by median
df['Age']= df['Age'].fillna(median)

In [26]:
dummies = pd.get_dummies(df['Sex']).astype('int')
dummies.head(2)

female  male
0       0     1
1       1     0

In [27]:
final = pd.concat([df, dummies], axis='columns')
final.head()

Pclass     Sex   Age     Fare  Survived  female  male
0       3    male  22.0   7.2500         0       0     1
1       1  female  38.0  71.2833         1       1     0
2       3  female  26.0   7.9250         1       1     0
3       1  female  35.0  53.1000         1       1     0
4       3    male  35.0   8.0500         0       0     1

In [28]:
x = df.drop(['Survived', 'Sex'], axis='columns')
x.head(2)

Pclass   Age     Fare
0       3  22.0   7.2500
1       1  38.0  71.2833

In [29]:
y = df['Survived']

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [31]:
len(x_train)

668

In [32]:
len(x_test)

223

In [33]:
# model building
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [34]:
model.score(x_test, y_test)

0.7130044843049327

In [35]:
model.predict(x_test)

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0])

In [36]:
model.predict_proba(x_test[0:10])

array([[0.45440673, 0.54559327],
       [0.85746038, 0.14253962],
       [0.88143987, 0.11856013],
       [0.88424402, 0.11575598],
       [0.76452191, 0.23547809],
       [0.73108916, 0.26891084],
       [0.45738972, 0.54261028],
       [0.73345796, 0.26654204],
       [0.8441902 , 0.1558098 ],
       [0.88316297, 0.11683703]])

#cross_val_score

In [37]:
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(GaussianNB(), x_train, y_train, cv=5)

array([0.67164179, 0.73880597, 0.67164179, 0.62406015, 0.59398496])