<a href="https://colab.research.google.com/github/Pushpalatha-H/ML/blob/main/2_linear_reg_multivariative_and__exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ML with python: Linear Regression Multiple Variables

Sample problem of predicting home price in monroe, new jersey (USA)
Below is the table containing home prices in monroe twp, NJ. Here price depends on area (square feet), bed rooms and age of the home (in years). Given these prices we have to predict prices of new homes based on area, bed rooms and age.


Given these home prices find out price of a home that has,

3000 sqr ft area, 3 bedrooms, 40 year old

2500 sqr ft area, 4 bedrooms, 5 year old

In [62]:
# importing pre-requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [63]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [64]:
median = df['bedrooms'].median()

In [65]:
df['bedrooms'] = df['bedrooms'].fillna(median)

In [66]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [67]:
x = df.drop('price', axis = 'columns')
y = df['price']

In [68]:
x

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [69]:
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

# Build model using linear_regression

In [70]:
from sklearn import linear_model

In [71]:
model = linear_model.LinearRegression()

In [72]:
model.fit(x,y)

LinearRegression()

In [73]:
model.score

<bound method RegressorMixin.score of LinearRegression()>

In [74]:
model.predict([[3000,3,15]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([579201.19929613])

In [75]:
model.predict([[1200, 2, 0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([402575.69235184])

#Exercise

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score



In [76]:
import pandas as pd
import numpy as np
!pip install word2number
from word2number import w2n
import matplotlib.pyplot as plt
%matplotlib inline

In [77]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [78]:
df['experience'] = df['experience'].fillna('zero')

In [79]:
mean = df['test_score(out of 10)'].mean()

In [80]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean)

In [81]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero               8.000000                           9      50000
1       zero               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [84]:
# convert df['experience'] to numbers using w2n.word_to_number
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [85]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [89]:
x = df.drop('salary($)', axis ='columns')
x.head()

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6

In [91]:
y = df['salary($)']
y.head()

0    50000
1    45000
2    60000
3    65000
4    70000
Name: salary($), dtype: int64

In [93]:
# model building
from sklearn import linear_model
model = linear_model.LinearRegression()

In [94]:
model.fit(x, y)

LinearRegression()

In [97]:
model.score(x,y)

0.9639958361860579

2 yr experience, 9 test score, 6 interview score



In [98]:
model.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53290.89255945])

12 yr experience, 10 test score, 10 interview score

In [99]:
model.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92268.07227784])