<a href="https://colab.research.google.com/github/Pushpalatha-H/ML/blob/main/4_save_and_load_model_using_pickle_and_joblib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# To save and load the model using pickle and joblib

In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/4_save_model/homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
from sklearn import linear_model
model = linear_model.LinearRegression()

In [4]:
x = df.drop('price', axis = 'columns')
y = df['price']

In [5]:
model.fit(x,y)

LinearRegression()

In [6]:
model.score(x,y)

0.9584301138199486

## load the model and save it by using pickle

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as file:
  pickle.dump(model, file)

In [9]:
with open('model_pickle','rb') as file:
  mp = pickle.load(file)

In [15]:
mp.coef_

array([135.78767123])

In [16]:
mp.intercept_

180616.43835616432

In [20]:
mp.predict([[7200]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1158287.67123288])

## load model and save using joblib

In [10]:
!pip install joblib

In [11]:
import joblib

In [12]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [14]:
mj =joblib.load('model_joblib')

In [21]:
mj.predict([[2000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([452191.78082192])

In [17]:
mj.coef_

array([135.78767123])

In [18]:
mj.intercept_

180616.43835616432